### ISSUE TITLE
investigate and document how to setup Racer 

### ISSUE THREAD

**Issue by fprezado** [Eclipse-SDV-Hackathon-BCX/hackchallenge-simulation#10]

**Comment by msmarioo** [comment]
Following instructions found here:
[JetRacer AI Kit](https://www.waveshare.com/wiki/JetRacer_AI_Kit)

Besides the installation of the base software, the following items will be added
- Chariott 
- Kuksa Val

**Comment by msmarioo** [comment]
Document the installation on a separate page

**Comment by fprezado** [comment]
completed

**Comment by msmarioo** [comment]
Created the following documentation:
- Added Chariott
- Added KUKSA.val server
- 
https://github.com/Eclipse-SDV-Hackathon-BCX/.github/blob/main/profile/JetRacer.md
