### ISSUE TITLE
investigate and document chariott python sample

### ISSUE THREAD

**Issue by fprezado** [Eclipse-SDV-Hackathon-BCX/hackchallenge-simulation#7]

**Comment by msmarioo** [comment]
Goal is to reproduce the KV Demo using a python example.
As many of the hackers use python, and one of the simulation also, it will simplify getting started

**Comment by msmarioo** [comment]
Add the python demo as a separate link

**Comment by msmarioo** [comment]
Completed the demo and added a reference to it.
Eventually I will extend the demo to also demonstrate connections to velocitas
